{{- if and (not .Values.apiKey.existingSecret) .Values.apiKey.value }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "guidellm-runner.fullname" . }}-api-key
  labels:
    {{- include "guidellm-runner.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.apiKey.existingSecretKey }}: {{ .Values.apiKey.value | b64enc | quote }}
{{- end }}
